package Views;

import Controller.EventController;
import Models.Event;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel
 */

public class FormularioEvento extends javax.swing.JDialog {
 // Variable para almacenar el estado de confirmación.
    private boolean confirmar;

    // Instancia de EventController para gestionar operaciones con eventos.
    private EventController gestionEventos;

    // ID del evento que se está editando o consultando.
    private int eventoId;

    // Constructor para crear o editar un evento.
    public FormularioEvento(java.awt.Frame parent, boolean modal, EventController gestionEventos) {
        super(parent, modal); // Llama al constructor de la clase base (JDialog).
        this.gestionEventos = gestionEventos; // Inicializa el controlador de eventos.
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    // Devuelve el estado de confirmación.
    public boolean confirmacion() {
        return this.confirmar;
    }



    // Valida que los campos de nombre, fecha, recinto y precio no estén vacíos.
    private boolean validarEspaciosVacios() {
        return !txtNombre.getText().trim().isEmpty() &&
               !txtEnclosure.getText().trim().isEmpty() &&
               !txtFecha.getText().trim().isEmpty() &&
               !txtPrecio.getText().trim().isEmpty();
    }

    // Método para consultar un evento, validar entradas y retornar el objeto Event.
    public Event consultarEvento() {
        if (!validarEspaciosVacios()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben ser completados.", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
 

        // Crea un nuevo evento basado en los datos ingresados.
        Event eventoConsultado = new Event();
        eventoConsultado.setName(txtNombre.getText());
        eventoConsultado.setDate(txtFecha.getText());
        eventoConsultado.setEnclosure(txtEnclosure.getText());
        eventoConsultado.setPrice(Double.parseDouble(txtPrecio.getText()));

        return eventoConsultado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrecio = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtEnclosure = new javax.swing.JTextField();
        lblEnclosure = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 160, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 160, 30));

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 160, -1));

        txtEnclosure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnclosureActionPerformed(evt);
            }
        });
        jPanel1.add(txtEnclosure, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 160, -1));

        lblEnclosure.setForeground(new java.awt.Color(0, 0, 0));
        lblEnclosure.setText("Enclosure");
        jPanel1.add(lblEnclosure, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        lblHora.setForeground(new java.awt.Color(0, 0, 0));
        lblHora.setText("Precio");
        jPanel1.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        btnGuardar.setText("Guardar ");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 87, 41));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 84, 47));

        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Fecha");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Verificar si el controlador de eventos está inicializado
        if (this.gestionEventos == null) {
            JOptionPane.showMessageDialog(this, "Error: gestionEventos no está inicializado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Consultar los datos del evento desde el formulario
        Event evento = consultarEvento();
        if (evento == null) {
            // Si hubo un error en la validación (evento es null), no se guarda
            return;
        }

        // Si el ID del evento es mayor a 0, se trata de una actualización
        if (this.eventoId > 0) {
            evento.setId(this.eventoId); // Asignar el ID al evento para actualizar
            gestionEventos.actualizarEvento(evento); // Actualizar el evento existente
        } else {
            // Si el ID es 0, es un nuevo evento, lo creamos
            gestionEventos.crearEvento(evento); // Crear un nuevo evento
        }

        confirmar = true; // Indica que la acción ha sido confirmada
        dispose(); // Cerrar el formulario
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtEnclosureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnclosureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnclosureActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEnclosure;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtEnclosure;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
