
package main;


import Usuario.GUIUsuario;
import Views.GUICliente;
import Views.ViewPurchaseHistory;
import Views.GUIEvent;
import Views.TicketSales;
import Controller.BuyTicketFacade;
import ENTITY.ClaseUsuario;
/**
 *
 * @author Manuel
 */
public class Admin extends javax.swing.JFrame {
    private BuyTicketFacade buyTicketController; // Controlador de compra de tickets
    private ClaseUsuario usuarioActual; // Usuario actual

    public Admin(BuyTicketFacade buyTicketController, ClaseUsuario usuarioActual) {
        this.buyTicketController = buyTicketController;
        this.usuarioActual = usuarioActual;
        initComponents();
    }


    // Renombrado de ViewPurchaseHistory() a mostrarHistorialCompras()
    private void mostrarHistorialCompras() {
        // Crear instancia de ViewPurchaseHistory pasando buyTicketController y usuarioActual
        ViewPurchaseHistory historialCompra = new ViewPurchaseHistory();
        historialCompra.setVisible(true);
        historialCompra.setResizable(false);
        historialCompra.setLocationRelativeTo(null);
    }

    private void GUIUsuario() {
        GUIUsuario Usu = new GUIUsuario();
        Usu.setVisible(true);
        Usu.setResizable(false);
        Usu.setLocationRelativeTo(null);
    }

    private void TicketSales() {
        TicketSales Usu = new TicketSales();
        Usu.setVisible(true);
        Usu.setResizable(false);
        Usu.setLocationRelativeTo(null);
    }

    private void GUIEvent() {
        GUIEvent Usu = new GUIEvent();
        Usu.setVisible(true);
        Usu.setResizable(false);
        Usu.setLocationRelativeTo(null);
    }

    private void GUIClientes() {
        GUICliente cliente = new GUICliente();
        cliente.setVisible(true);
        cliente.setResizable(false);
        cliente.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnEventos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCliente1 = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnHistorial = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEventos.setBackground(new java.awt.Color(102, 102, 102));
        btnEventos.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        btnEventos.setForeground(new java.awt.Color(0, 0, 0));
        btnEventos.setText("Eventos");
        btnEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventosActionPerformed(evt);
            }
        });
        jPanel1.add(btnEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 114, 42));

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 74, 41));

        btnCliente1.setBackground(new java.awt.Color(102, 102, 102));
        btnCliente1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        btnCliente1.setForeground(new java.awt.Color(0, 0, 0));
        btnCliente1.setText("Cliente");
        btnCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliente1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 114, 42));

        btnTicket.setBackground(new java.awt.Color(102, 102, 102));
        btnTicket.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        btnTicket.setForeground(new java.awt.Color(0, 0, 0));
        btnTicket.setText("Ticket");
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });
        jPanel1.add(btnTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 114, 42));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Vista Administrador");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 190, -1));

        btnHistorial.setBackground(new java.awt.Color(102, 102, 102));
        btnHistorial.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(0, 0, 0));
        btnHistorial.setText("Historial");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 114, 42));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo Admin2.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Abre la GUI de TicketSales
        TicketSales ticketSales = new TicketSales();
        ticketSales.setVisible(true);
        ticketSales.setResizable(false);
        ticketSales.setLocationRelativeTo(null);

        // Cierra la ventana actual (Admin)
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventosActionPerformed
       GUIEvent();
    }//GEN-LAST:event_btnEventosActionPerformed

    private void btnCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliente1ActionPerformed
        GUIClientes();
    }//GEN-LAST:event_btnCliente1ActionPerformed

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        TicketSales();
    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        mostrarHistorialCompras();
    }//GEN-LAST:event_btnHistorialActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente1;
    private javax.swing.JButton btnEventos;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTicket;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
